image: debian/stable
packages:
  - nodejs
  - npm
  - rsync
sources:
  - https://git.sr.ht/~etalab/communs.numerique.gouv.fr
secrets:
  - 2a86c4c0-2935-4c33-8191-b1683862cc0c
tasks:
  - install: |
      cd communs.numerique.gouv.fr
      git checkout production
      npm install
      npx eleventy
  - upload: |
      rsync -e "ssh -o StrictHostKeyChecking=no" -av _site/* communs.numerique.gouv.fr:/home/build/websites/communs.numerique.gouv.fr/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@data.gouv.fr
