image: debian/stable
packages:
  - nodejs
  - npm
  - rsync
sources:
  - https://git.sr.ht/~etalab/communs.numerique.gouv.fr
secrets:
  - 878b8229-96a8-45a4-9ef7-99b7998dd1f8
tasks:
  - install: |
      cd communs.numerique.gouv.fr
      git checkout production
      npm install
      npx eleventy
  - upload: |
      rsync -e "ssh -o StrictHostKeyChecking=no" -av _site/* communs.numerique.gouv.fr:/home/build/websites/communs.numerique.gouv.fr/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@data.gouv.fr
