image: archlinux
packages:
  - nodejs
  - npm
  - rsync
secrets:
  - b2fbc53c-abc0-4d2a-b00e-15b6a2681788
tasks:
  - install: |
      cd communs.numerique.gouv.fr
      npm install
      npx eleventy
  - upload: |
      cd communs.numerique.gouv.fr
      rsync -e "ssh -o StrictHostKeyChecking=no" -av --delete _site/ web@libre-01.infra.data.gouv.fr:/home/web/websites/communs.numerique.gouv.fr_preprod/
triggers:
  - action: email
    condition: failure
    to: bastien.guerry@data.gouv.fr
